/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRunwayRouteImport } from './routes/_authenticated/runway'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedDesignRouteImport } from './routes/_authenticated/design'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCohortRouteImport } from './routes/_authenticated/cohort'
import { Route as AuthenticatedBoardroomRouteImport } from './routes/_authenticated/boardroom'
import { Route as AuthenticatedAuditsRouteImport } from './routes/_authenticated/audits'
import { Route as AuthGithubCallbackRouteImport } from './routes/auth_.github.callback'
import { Route as AuthenticatedRunwayProjectIdRouteImport } from './routes/_authenticated/runway_.$projectId'
import { Route as AuthenticatedPlanProjectIdRouteImport } from './routes/_authenticated/plan.$projectId'
import { Route as AuthenticatedIntakeIntakeIdRouteImport } from './routes/_authenticated/intake.$intakeId'
import { Route as AuthenticatedDesignProjectIdRouteImport } from './routes/_authenticated/design_.$projectId'
import { Route as AuthenticatedDebugRunsRouteImport } from './routes/_authenticated/debug.runs'
import { Route as AuthenticatedCohortProjectIdRouteImport } from './routes/_authenticated/cohort_.$projectId'
import { Route as AuthenticatedBoardroomProjectIdRouteImport } from './routes/_authenticated/boardroom_.$projectId'
import { Route as AuthenticatedAuditsProjectIdRouteImport } from './routes/_authenticated/audits_.$projectId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRunwayRoute = AuthenticatedRunwayRouteImport.update({
  id: '/runway',
  path: '/runway',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDesignRoute = AuthenticatedDesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCohortRoute = AuthenticatedCohortRouteImport.update({
  id: '/cohort',
  path: '/cohort',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBoardroomRoute = AuthenticatedBoardroomRouteImport.update({
  id: '/boardroom',
  path: '/boardroom',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditsRoute = AuthenticatedAuditsRouteImport.update({
  id: '/audits',
  path: '/audits',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthGithubCallbackRoute = AuthGithubCallbackRouteImport.update({
  id: '/auth_/github/callback',
  path: '/auth/github/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRunwayProjectIdRoute =
  AuthenticatedRunwayProjectIdRouteImport.update({
    id: '/runway_/$projectId',
    path: '/runway/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlanProjectIdRoute =
  AuthenticatedPlanProjectIdRouteImport.update({
    id: '/plan/$projectId',
    path: '/plan/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIntakeIntakeIdRoute =
  AuthenticatedIntakeIntakeIdRouteImport.update({
    id: '/intake/$intakeId',
    path: '/intake/$intakeId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDesignProjectIdRoute =
  AuthenticatedDesignProjectIdRouteImport.update({
    id: '/design_/$projectId',
    path: '/design/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDebugRunsRoute = AuthenticatedDebugRunsRouteImport.update({
  id: '/debug/runs',
  path: '/debug/runs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCohortProjectIdRoute =
  AuthenticatedCohortProjectIdRouteImport.update({
    id: '/cohort_/$projectId',
    path: '/cohort/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBoardroomProjectIdRoute =
  AuthenticatedBoardroomProjectIdRouteImport.update({
    id: '/boardroom_/$projectId',
    path: '/boardroom/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAuditsProjectIdRoute =
  AuthenticatedAuditsProjectIdRouteImport.update({
    id: '/audits_/$projectId',
    path: '/audits/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/audits': typeof AuthenticatedAuditsRoute
  '/boardroom': typeof AuthenticatedBoardroomRoute
  '/cohort': typeof AuthenticatedCohortRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/design': typeof AuthenticatedDesignRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/runway': typeof AuthenticatedRunwayRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/audits/$projectId': typeof AuthenticatedAuditsProjectIdRoute
  '/boardroom/$projectId': typeof AuthenticatedBoardroomProjectIdRoute
  '/cohort/$projectId': typeof AuthenticatedCohortProjectIdRoute
  '/debug/runs': typeof AuthenticatedDebugRunsRoute
  '/design/$projectId': typeof AuthenticatedDesignProjectIdRoute
  '/intake/$intakeId': typeof AuthenticatedIntakeIntakeIdRoute
  '/plan/$projectId': typeof AuthenticatedPlanProjectIdRoute
  '/runway/$projectId': typeof AuthenticatedRunwayProjectIdRoute
  '/auth/github/callback': typeof AuthGithubCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/audits': typeof AuthenticatedAuditsRoute
  '/boardroom': typeof AuthenticatedBoardroomRoute
  '/cohort': typeof AuthenticatedCohortRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/design': typeof AuthenticatedDesignRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/runway': typeof AuthenticatedRunwayRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/audits/$projectId': typeof AuthenticatedAuditsProjectIdRoute
  '/boardroom/$projectId': typeof AuthenticatedBoardroomProjectIdRoute
  '/cohort/$projectId': typeof AuthenticatedCohortProjectIdRoute
  '/debug/runs': typeof AuthenticatedDebugRunsRoute
  '/design/$projectId': typeof AuthenticatedDesignProjectIdRoute
  '/intake/$intakeId': typeof AuthenticatedIntakeIntakeIdRoute
  '/plan/$projectId': typeof AuthenticatedPlanProjectIdRoute
  '/runway/$projectId': typeof AuthenticatedRunwayProjectIdRoute
  '/auth/github/callback': typeof AuthGithubCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/audits': typeof AuthenticatedAuditsRoute
  '/_authenticated/boardroom': typeof AuthenticatedBoardroomRoute
  '/_authenticated/cohort': typeof AuthenticatedCohortRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/design': typeof AuthenticatedDesignRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/runway': typeof AuthenticatedRunwayRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/audits_/$projectId': typeof AuthenticatedAuditsProjectIdRoute
  '/_authenticated/boardroom_/$projectId': typeof AuthenticatedBoardroomProjectIdRoute
  '/_authenticated/cohort_/$projectId': typeof AuthenticatedCohortProjectIdRoute
  '/_authenticated/debug/runs': typeof AuthenticatedDebugRunsRoute
  '/_authenticated/design_/$projectId': typeof AuthenticatedDesignProjectIdRoute
  '/_authenticated/intake/$intakeId': typeof AuthenticatedIntakeIntakeIdRoute
  '/_authenticated/plan/$projectId': typeof AuthenticatedPlanProjectIdRoute
  '/_authenticated/runway_/$projectId': typeof AuthenticatedRunwayProjectIdRoute
  '/auth_/github/callback': typeof AuthGithubCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/audits'
    | '/boardroom'
    | '/cohort'
    | '/dashboard'
    | '/design'
    | '/onboarding'
    | '/runway'
    | '/settings'
    | '/audits/$projectId'
    | '/boardroom/$projectId'
    | '/cohort/$projectId'
    | '/debug/runs'
    | '/design/$projectId'
    | '/intake/$intakeId'
    | '/plan/$projectId'
    | '/runway/$projectId'
    | '/auth/github/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/audits'
    | '/boardroom'
    | '/cohort'
    | '/dashboard'
    | '/design'
    | '/onboarding'
    | '/runway'
    | '/settings'
    | '/audits/$projectId'
    | '/boardroom/$projectId'
    | '/cohort/$projectId'
    | '/debug/runs'
    | '/design/$projectId'
    | '/intake/$intakeId'
    | '/plan/$projectId'
    | '/runway/$projectId'
    | '/auth/github/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/audits'
    | '/_authenticated/boardroom'
    | '/_authenticated/cohort'
    | '/_authenticated/dashboard'
    | '/_authenticated/design'
    | '/_authenticated/onboarding'
    | '/_authenticated/runway'
    | '/_authenticated/settings'
    | '/_authenticated/audits_/$projectId'
    | '/_authenticated/boardroom_/$projectId'
    | '/_authenticated/cohort_/$projectId'
    | '/_authenticated/debug/runs'
    | '/_authenticated/design_/$projectId'
    | '/_authenticated/intake/$intakeId'
    | '/_authenticated/plan/$projectId'
    | '/_authenticated/runway_/$projectId'
    | '/auth_/github/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AuthGithubCallbackRoute: typeof AuthGithubCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/runway': {
      id: '/_authenticated/runway'
      path: '/runway'
      fullPath: '/runway'
      preLoaderRoute: typeof AuthenticatedRunwayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/design': {
      id: '/_authenticated/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof AuthenticatedDesignRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cohort': {
      id: '/_authenticated/cohort'
      path: '/cohort'
      fullPath: '/cohort'
      preLoaderRoute: typeof AuthenticatedCohortRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/boardroom': {
      id: '/_authenticated/boardroom'
      path: '/boardroom'
      fullPath: '/boardroom'
      preLoaderRoute: typeof AuthenticatedBoardroomRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audits': {
      id: '/_authenticated/audits'
      path: '/audits'
      fullPath: '/audits'
      preLoaderRoute: typeof AuthenticatedAuditsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth_/github/callback': {
      id: '/auth_/github/callback'
      path: '/auth/github/callback'
      fullPath: '/auth/github/callback'
      preLoaderRoute: typeof AuthGithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/runway_/$projectId': {
      id: '/_authenticated/runway_/$projectId'
      path: '/runway/$projectId'
      fullPath: '/runway/$projectId'
      preLoaderRoute: typeof AuthenticatedRunwayProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plan/$projectId': {
      id: '/_authenticated/plan/$projectId'
      path: '/plan/$projectId'
      fullPath: '/plan/$projectId'
      preLoaderRoute: typeof AuthenticatedPlanProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/intake/$intakeId': {
      id: '/_authenticated/intake/$intakeId'
      path: '/intake/$intakeId'
      fullPath: '/intake/$intakeId'
      preLoaderRoute: typeof AuthenticatedIntakeIntakeIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/design_/$projectId': {
      id: '/_authenticated/design_/$projectId'
      path: '/design/$projectId'
      fullPath: '/design/$projectId'
      preLoaderRoute: typeof AuthenticatedDesignProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/debug/runs': {
      id: '/_authenticated/debug/runs'
      path: '/debug/runs'
      fullPath: '/debug/runs'
      preLoaderRoute: typeof AuthenticatedDebugRunsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cohort_/$projectId': {
      id: '/_authenticated/cohort_/$projectId'
      path: '/cohort/$projectId'
      fullPath: '/cohort/$projectId'
      preLoaderRoute: typeof AuthenticatedCohortProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/boardroom_/$projectId': {
      id: '/_authenticated/boardroom_/$projectId'
      path: '/boardroom/$projectId'
      fullPath: '/boardroom/$projectId'
      preLoaderRoute: typeof AuthenticatedBoardroomProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audits_/$projectId': {
      id: '/_authenticated/audits_/$projectId'
      path: '/audits/$projectId'
      fullPath: '/audits/$projectId'
      preLoaderRoute: typeof AuthenticatedAuditsProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAuditsRoute: typeof AuthenticatedAuditsRoute
  AuthenticatedBoardroomRoute: typeof AuthenticatedBoardroomRoute
  AuthenticatedCohortRoute: typeof AuthenticatedCohortRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDesignRoute: typeof AuthenticatedDesignRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedRunwayRoute: typeof AuthenticatedRunwayRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedAuditsProjectIdRoute: typeof AuthenticatedAuditsProjectIdRoute
  AuthenticatedBoardroomProjectIdRoute: typeof AuthenticatedBoardroomProjectIdRoute
  AuthenticatedCohortProjectIdRoute: typeof AuthenticatedCohortProjectIdRoute
  AuthenticatedDebugRunsRoute: typeof AuthenticatedDebugRunsRoute
  AuthenticatedDesignProjectIdRoute: typeof AuthenticatedDesignProjectIdRoute
  AuthenticatedIntakeIntakeIdRoute: typeof AuthenticatedIntakeIntakeIdRoute
  AuthenticatedPlanProjectIdRoute: typeof AuthenticatedPlanProjectIdRoute
  AuthenticatedRunwayProjectIdRoute: typeof AuthenticatedRunwayProjectIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAuditsRoute: AuthenticatedAuditsRoute,
  AuthenticatedBoardroomRoute: AuthenticatedBoardroomRoute,
  AuthenticatedCohortRoute: AuthenticatedCohortRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDesignRoute: AuthenticatedDesignRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedRunwayRoute: AuthenticatedRunwayRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedAuditsProjectIdRoute: AuthenticatedAuditsProjectIdRoute,
  AuthenticatedBoardroomProjectIdRoute: AuthenticatedBoardroomProjectIdRoute,
  AuthenticatedCohortProjectIdRoute: AuthenticatedCohortProjectIdRoute,
  AuthenticatedDebugRunsRoute: AuthenticatedDebugRunsRoute,
  AuthenticatedDesignProjectIdRoute: AuthenticatedDesignProjectIdRoute,
  AuthenticatedIntakeIntakeIdRoute: AuthenticatedIntakeIntakeIdRoute,
  AuthenticatedPlanProjectIdRoute: AuthenticatedPlanProjectIdRoute,
  AuthenticatedRunwayProjectIdRoute: AuthenticatedRunwayProjectIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AuthGithubCallbackRoute: AuthGithubCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
