/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRunwayRouteImport } from './routes/_authenticated/runway'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedDesignRouteImport } from './routes/_authenticated/design'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCohortRouteImport } from './routes/_authenticated/cohort'
import { Route as AuthenticatedBoardroomRouteImport } from './routes/_authenticated/boardroom'
import { Route as AuthenticatedAuditsRouteImport } from './routes/_authenticated/audits'
import { Route as AuthGithubCallbackRouteImport } from './routes/auth.github.callback'
import { Route as AuthenticatedRunwayProjectIdRouteImport } from './routes/_authenticated/runway.$projectId'
import { Route as AuthenticatedPlanProjectIdRouteImport } from './routes/_authenticated/plan.$projectId'
import { Route as AuthenticatedIntakeIntakeIdRouteImport } from './routes/_authenticated/intake.$intakeId'
import { Route as AuthenticatedDesignProjectIdRouteImport } from './routes/_authenticated/design.$projectId'
import { Route as AuthenticatedDebugRunsRouteImport } from './routes/_authenticated/debug.runs'
import { Route as AuthenticatedBoardroomProjectIdRouteImport } from './routes/_authenticated/boardroom.$projectId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRunwayRoute = AuthenticatedRunwayRouteImport.update({
  id: '/runway',
  path: '/runway',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDesignRoute = AuthenticatedDesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCohortRoute = AuthenticatedCohortRouteImport.update({
  id: '/cohort',
  path: '/cohort',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBoardroomRoute = AuthenticatedBoardroomRouteImport.update({
  id: '/boardroom',
  path: '/boardroom',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditsRoute = AuthenticatedAuditsRouteImport.update({
  id: '/audits',
  path: '/audits',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthGithubCallbackRoute = AuthGithubCallbackRouteImport.update({
  id: '/github/callback',
  path: '/github/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedRunwayProjectIdRoute =
  AuthenticatedRunwayProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => AuthenticatedRunwayRoute,
  } as any)
const AuthenticatedPlanProjectIdRoute =
  AuthenticatedPlanProjectIdRouteImport.update({
    id: '/plan/$projectId',
    path: '/plan/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIntakeIntakeIdRoute =
  AuthenticatedIntakeIntakeIdRouteImport.update({
    id: '/intake/$intakeId',
    path: '/intake/$intakeId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDesignProjectIdRoute =
  AuthenticatedDesignProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => AuthenticatedDesignRoute,
  } as any)
const AuthenticatedDebugRunsRoute = AuthenticatedDebugRunsRouteImport.update({
  id: '/debug/runs',
  path: '/debug/runs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBoardroomProjectIdRoute =
  AuthenticatedBoardroomProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => AuthenticatedBoardroomRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/audits': typeof AuthenticatedAuditsRoute
  '/boardroom': typeof AuthenticatedBoardroomRouteWithChildren
  '/cohort': typeof AuthenticatedCohortRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/design': typeof AuthenticatedDesignRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/runway': typeof AuthenticatedRunwayRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/boardroom/$projectId': typeof AuthenticatedBoardroomProjectIdRoute
  '/debug/runs': typeof AuthenticatedDebugRunsRoute
  '/design/$projectId': typeof AuthenticatedDesignProjectIdRoute
  '/intake/$intakeId': typeof AuthenticatedIntakeIntakeIdRoute
  '/plan/$projectId': typeof AuthenticatedPlanProjectIdRoute
  '/runway/$projectId': typeof AuthenticatedRunwayProjectIdRoute
  '/auth/github/callback': typeof AuthGithubCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/audits': typeof AuthenticatedAuditsRoute
  '/boardroom': typeof AuthenticatedBoardroomRouteWithChildren
  '/cohort': typeof AuthenticatedCohortRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/design': typeof AuthenticatedDesignRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/runway': typeof AuthenticatedRunwayRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/boardroom/$projectId': typeof AuthenticatedBoardroomProjectIdRoute
  '/debug/runs': typeof AuthenticatedDebugRunsRoute
  '/design/$projectId': typeof AuthenticatedDesignProjectIdRoute
  '/intake/$intakeId': typeof AuthenticatedIntakeIntakeIdRoute
  '/plan/$projectId': typeof AuthenticatedPlanProjectIdRoute
  '/runway/$projectId': typeof AuthenticatedRunwayProjectIdRoute
  '/auth/github/callback': typeof AuthGithubCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_authenticated/audits': typeof AuthenticatedAuditsRoute
  '/_authenticated/boardroom': typeof AuthenticatedBoardroomRouteWithChildren
  '/_authenticated/cohort': typeof AuthenticatedCohortRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/design': typeof AuthenticatedDesignRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/runway': typeof AuthenticatedRunwayRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/boardroom/$projectId': typeof AuthenticatedBoardroomProjectIdRoute
  '/_authenticated/debug/runs': typeof AuthenticatedDebugRunsRoute
  '/_authenticated/design/$projectId': typeof AuthenticatedDesignProjectIdRoute
  '/_authenticated/intake/$intakeId': typeof AuthenticatedIntakeIntakeIdRoute
  '/_authenticated/plan/$projectId': typeof AuthenticatedPlanProjectIdRoute
  '/_authenticated/runway/$projectId': typeof AuthenticatedRunwayProjectIdRoute
  '/auth/github/callback': typeof AuthGithubCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/audits'
    | '/boardroom'
    | '/cohort'
    | '/dashboard'
    | '/design'
    | '/onboarding'
    | '/runway'
    | '/settings'
    | '/boardroom/$projectId'
    | '/debug/runs'
    | '/design/$projectId'
    | '/intake/$intakeId'
    | '/plan/$projectId'
    | '/runway/$projectId'
    | '/auth/github/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/audits'
    | '/boardroom'
    | '/cohort'
    | '/dashboard'
    | '/design'
    | '/onboarding'
    | '/runway'
    | '/settings'
    | '/boardroom/$projectId'
    | '/debug/runs'
    | '/design/$projectId'
    | '/intake/$intakeId'
    | '/plan/$projectId'
    | '/runway/$projectId'
    | '/auth/github/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/audits'
    | '/_authenticated/boardroom'
    | '/_authenticated/cohort'
    | '/_authenticated/dashboard'
    | '/_authenticated/design'
    | '/_authenticated/onboarding'
    | '/_authenticated/runway'
    | '/_authenticated/settings'
    | '/_authenticated/boardroom/$projectId'
    | '/_authenticated/debug/runs'
    | '/_authenticated/design/$projectId'
    | '/_authenticated/intake/$intakeId'
    | '/_authenticated/plan/$projectId'
    | '/_authenticated/runway/$projectId'
    | '/auth/github/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/runway': {
      id: '/_authenticated/runway'
      path: '/runway'
      fullPath: '/runway'
      preLoaderRoute: typeof AuthenticatedRunwayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/design': {
      id: '/_authenticated/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof AuthenticatedDesignRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cohort': {
      id: '/_authenticated/cohort'
      path: '/cohort'
      fullPath: '/cohort'
      preLoaderRoute: typeof AuthenticatedCohortRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/boardroom': {
      id: '/_authenticated/boardroom'
      path: '/boardroom'
      fullPath: '/boardroom'
      preLoaderRoute: typeof AuthenticatedBoardroomRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audits': {
      id: '/_authenticated/audits'
      path: '/audits'
      fullPath: '/audits'
      preLoaderRoute: typeof AuthenticatedAuditsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/github/callback': {
      id: '/auth/github/callback'
      path: '/github/callback'
      fullPath: '/auth/github/callback'
      preLoaderRoute: typeof AuthGithubCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/runway/$projectId': {
      id: '/_authenticated/runway/$projectId'
      path: '/$projectId'
      fullPath: '/runway/$projectId'
      preLoaderRoute: typeof AuthenticatedRunwayProjectIdRouteImport
      parentRoute: typeof AuthenticatedRunwayRoute
    }
    '/_authenticated/plan/$projectId': {
      id: '/_authenticated/plan/$projectId'
      path: '/plan/$projectId'
      fullPath: '/plan/$projectId'
      preLoaderRoute: typeof AuthenticatedPlanProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/intake/$intakeId': {
      id: '/_authenticated/intake/$intakeId'
      path: '/intake/$intakeId'
      fullPath: '/intake/$intakeId'
      preLoaderRoute: typeof AuthenticatedIntakeIntakeIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/design/$projectId': {
      id: '/_authenticated/design/$projectId'
      path: '/$projectId'
      fullPath: '/design/$projectId'
      preLoaderRoute: typeof AuthenticatedDesignProjectIdRouteImport
      parentRoute: typeof AuthenticatedDesignRoute
    }
    '/_authenticated/debug/runs': {
      id: '/_authenticated/debug/runs'
      path: '/debug/runs'
      fullPath: '/debug/runs'
      preLoaderRoute: typeof AuthenticatedDebugRunsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/boardroom/$projectId': {
      id: '/_authenticated/boardroom/$projectId'
      path: '/$projectId'
      fullPath: '/boardroom/$projectId'
      preLoaderRoute: typeof AuthenticatedBoardroomProjectIdRouteImport
      parentRoute: typeof AuthenticatedBoardroomRoute
    }
  }
}

interface AuthenticatedBoardroomRouteChildren {
  AuthenticatedBoardroomProjectIdRoute: typeof AuthenticatedBoardroomProjectIdRoute
}

const AuthenticatedBoardroomRouteChildren: AuthenticatedBoardroomRouteChildren =
  {
    AuthenticatedBoardroomProjectIdRoute: AuthenticatedBoardroomProjectIdRoute,
  }

const AuthenticatedBoardroomRouteWithChildren =
  AuthenticatedBoardroomRoute._addFileChildren(
    AuthenticatedBoardroomRouteChildren,
  )

interface AuthenticatedDesignRouteChildren {
  AuthenticatedDesignProjectIdRoute: typeof AuthenticatedDesignProjectIdRoute
}

const AuthenticatedDesignRouteChildren: AuthenticatedDesignRouteChildren = {
  AuthenticatedDesignProjectIdRoute: AuthenticatedDesignProjectIdRoute,
}

const AuthenticatedDesignRouteWithChildren =
  AuthenticatedDesignRoute._addFileChildren(AuthenticatedDesignRouteChildren)

interface AuthenticatedRunwayRouteChildren {
  AuthenticatedRunwayProjectIdRoute: typeof AuthenticatedRunwayProjectIdRoute
}

const AuthenticatedRunwayRouteChildren: AuthenticatedRunwayRouteChildren = {
  AuthenticatedRunwayProjectIdRoute: AuthenticatedRunwayProjectIdRoute,
}

const AuthenticatedRunwayRouteWithChildren =
  AuthenticatedRunwayRoute._addFileChildren(AuthenticatedRunwayRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAuditsRoute: typeof AuthenticatedAuditsRoute
  AuthenticatedBoardroomRoute: typeof AuthenticatedBoardroomRouteWithChildren
  AuthenticatedCohortRoute: typeof AuthenticatedCohortRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDesignRoute: typeof AuthenticatedDesignRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedRunwayRoute: typeof AuthenticatedRunwayRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedDebugRunsRoute: typeof AuthenticatedDebugRunsRoute
  AuthenticatedIntakeIntakeIdRoute: typeof AuthenticatedIntakeIntakeIdRoute
  AuthenticatedPlanProjectIdRoute: typeof AuthenticatedPlanProjectIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAuditsRoute: AuthenticatedAuditsRoute,
  AuthenticatedBoardroomRoute: AuthenticatedBoardroomRouteWithChildren,
  AuthenticatedCohortRoute: AuthenticatedCohortRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDesignRoute: AuthenticatedDesignRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedRunwayRoute: AuthenticatedRunwayRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedDebugRunsRoute: AuthenticatedDebugRunsRoute,
  AuthenticatedIntakeIntakeIdRoute: AuthenticatedIntakeIntakeIdRoute,
  AuthenticatedPlanProjectIdRoute: AuthenticatedPlanProjectIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthGithubCallbackRoute: typeof AuthGithubCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthGithubCallbackRoute: AuthGithubCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
