/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRunwayRouteImport } from './routes/_authenticated/runway'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedDesignRouteImport } from './routes/_authenticated/design'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCohortRouteImport } from './routes/_authenticated/cohort'
import { Route as AuthenticatedBoardroomRouteImport } from './routes/_authenticated/boardroom'
import { Route as AuthenticatedAuditsRouteImport } from './routes/_authenticated/audits'
import { Route as AuthenticatedIntakeIntakeIdRouteImport } from './routes/_authenticated/intake.$intakeId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRunwayRoute = AuthenticatedRunwayRouteImport.update({
  id: '/runway',
  path: '/runway',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDesignRoute = AuthenticatedDesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCohortRoute = AuthenticatedCohortRouteImport.update({
  id: '/cohort',
  path: '/cohort',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBoardroomRoute = AuthenticatedBoardroomRouteImport.update({
  id: '/boardroom',
  path: '/boardroom',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditsRoute = AuthenticatedAuditsRouteImport.update({
  id: '/audits',
  path: '/audits',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntakeIntakeIdRoute =
  AuthenticatedIntakeIntakeIdRouteImport.update({
    id: '/intake/$intakeId',
    path: '/intake/$intakeId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/audits': typeof AuthenticatedAuditsRoute
  '/boardroom': typeof AuthenticatedBoardroomRoute
  '/cohort': typeof AuthenticatedCohortRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/design': typeof AuthenticatedDesignRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/runway': typeof AuthenticatedRunwayRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/intake/$intakeId': typeof AuthenticatedIntakeIntakeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/audits': typeof AuthenticatedAuditsRoute
  '/boardroom': typeof AuthenticatedBoardroomRoute
  '/cohort': typeof AuthenticatedCohortRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/design': typeof AuthenticatedDesignRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/runway': typeof AuthenticatedRunwayRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/intake/$intakeId': typeof AuthenticatedIntakeIntakeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/audits': typeof AuthenticatedAuditsRoute
  '/_authenticated/boardroom': typeof AuthenticatedBoardroomRoute
  '/_authenticated/cohort': typeof AuthenticatedCohortRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/design': typeof AuthenticatedDesignRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/runway': typeof AuthenticatedRunwayRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/intake/$intakeId': typeof AuthenticatedIntakeIntakeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/audits'
    | '/boardroom'
    | '/cohort'
    | '/dashboard'
    | '/design'
    | '/onboarding'
    | '/runway'
    | '/settings'
    | '/intake/$intakeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/audits'
    | '/boardroom'
    | '/cohort'
    | '/dashboard'
    | '/design'
    | '/onboarding'
    | '/runway'
    | '/settings'
    | '/intake/$intakeId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/audits'
    | '/_authenticated/boardroom'
    | '/_authenticated/cohort'
    | '/_authenticated/dashboard'
    | '/_authenticated/design'
    | '/_authenticated/onboarding'
    | '/_authenticated/runway'
    | '/_authenticated/settings'
    | '/_authenticated/intake/$intakeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/runway': {
      id: '/_authenticated/runway'
      path: '/runway'
      fullPath: '/runway'
      preLoaderRoute: typeof AuthenticatedRunwayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/design': {
      id: '/_authenticated/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof AuthenticatedDesignRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cohort': {
      id: '/_authenticated/cohort'
      path: '/cohort'
      fullPath: '/cohort'
      preLoaderRoute: typeof AuthenticatedCohortRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/boardroom': {
      id: '/_authenticated/boardroom'
      path: '/boardroom'
      fullPath: '/boardroom'
      preLoaderRoute: typeof AuthenticatedBoardroomRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audits': {
      id: '/_authenticated/audits'
      path: '/audits'
      fullPath: '/audits'
      preLoaderRoute: typeof AuthenticatedAuditsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/intake/$intakeId': {
      id: '/_authenticated/intake/$intakeId'
      path: '/intake/$intakeId'
      fullPath: '/intake/$intakeId'
      preLoaderRoute: typeof AuthenticatedIntakeIntakeIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAuditsRoute: typeof AuthenticatedAuditsRoute
  AuthenticatedBoardroomRoute: typeof AuthenticatedBoardroomRoute
  AuthenticatedCohortRoute: typeof AuthenticatedCohortRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDesignRoute: typeof AuthenticatedDesignRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedRunwayRoute: typeof AuthenticatedRunwayRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIntakeIntakeIdRoute: typeof AuthenticatedIntakeIntakeIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAuditsRoute: AuthenticatedAuditsRoute,
  AuthenticatedBoardroomRoute: AuthenticatedBoardroomRoute,
  AuthenticatedCohortRoute: AuthenticatedCohortRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDesignRoute: AuthenticatedDesignRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedRunwayRoute: AuthenticatedRunwayRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIntakeIntakeIdRoute: AuthenticatedIntakeIntakeIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
